"""
BrandPulse AI - Pydantic Schemas
"""
from app.schemas.user import UserCreate, UserResponse, Token, TokenData
from app.schemas.business import (
    BusinessCreate,
    BusinessUpdate,
    BusinessResponse,
    OnboardingRequest,
    OnboardingResponse,
)
from app.schemas.competitor import (
    CompetitorCreate,
    CompetitorResponse,
    CompetitorAnalysis,
)
from app.schemas.content import (
    ContentGenerationRequest,
    GeneratedContentResponse,
    CalendarResponse,
    ContentExport,
    EngagementPrediction,
    ViralScanRequest,
    ViralOpportunity,
)
from app.schemas.ml import (
    MLPredictionRequest,
    MLFullPrediction,
    EngagementPredictionML,
    FormatRecommendation,
    TriggerSuggestions,
    HybridContentRequest,
    HybridContentResponse,
    ModelTrainingRequest,
    ModelTrainingResponse,
    ModelStatusResponse,
)
from app.schemas.kpi_weights import (
    EngagementWeights,
    KPIWeightsCreate,
    KPIWeightsResponse,
    KPIWeightsPreview,
    MultiOutputPrediction,
    MultiOutputPredictionRequest,
    MultiOutputPredictionResponse,
    KPITemplate,
    KPITemplatesResponse,
    KPI_TEMPLATES,
)

__all__ = [
    "UserCreate",
    "UserResponse",
    "Token",
    "TokenData",
    "BusinessCreate",
    "BusinessUpdate",
    "BusinessResponse",
    "OnboardingRequest",
    "OnboardingResponse",
    "CompetitorCreate",
    "CompetitorResponse",
    "CompetitorAnalysis",
    "ContentGenerationRequest",
    "GeneratedContentResponse",
    "CalendarResponse",
    "ContentExport",
    "EngagementPrediction",
    "ViralScanRequest",
    "ViralOpportunity",
    "MLPredictionRequest",
    "MLFullPrediction",
    "EngagementPredictionML",
    "FormatRecommendation",
    "TriggerSuggestions",
    "HybridContentRequest",
    "HybridContentResponse",
    "ModelTrainingRequest",
    "ModelTrainingResponse",
    "ModelStatusResponse",
    "EngagementWeights",
    "KPIWeightsCreate",
    "KPIWeightsResponse",
    "KPIWeightsPreview",
    "MultiOutputPrediction",
    "MultiOutputPredictionRequest",
    "MultiOutputPredictionResponse",
    "KPITemplate",
    "KPITemplatesResponse",
    "KPI_TEMPLATES",
]
